// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATqj_Z6lUO8kS90WYLOwNL84dDSI5AYUA',
    appId: '1:781581390170:web:7e8a5a937ad3a684176363',
    messagingSenderId: '781581390170',
    projectId: 'intsagram-clone-4918f',
    authDomain: 'intsagram-clone-4918f.firebaseapp.com',
    storageBucket: 'intsagram-clone-4918f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN2vVY6VkClNFF-bxhtcIl7hEDIWfaBxQ',
    appId: '1:781581390170:android:fb859030d7153b4d176363',
    messagingSenderId: '781581390170',
    projectId: 'intsagram-clone-4918f',
    storageBucket: 'intsagram-clone-4918f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdvW9UYpfgWPYHbbTmgNqOKOi2S-nd8E',
    appId: '1:781581390170:ios:eb772ed0b7146d5a176363',
    messagingSenderId: '781581390170',
    projectId: 'intsagram-clone-4918f',
    storageBucket: 'intsagram-clone-4918f.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATqj_Z6lUO8kS90WYLOwNL84dDSI5AYUA',
    appId: '1:781581390170:web:3b30b0c0d0e07267176363',
    messagingSenderId: '781581390170',
    projectId: 'intsagram-clone-4918f',
    authDomain: 'intsagram-clone-4918f.firebaseapp.com',
    storageBucket: 'intsagram-clone-4918f.appspot.com',
  );
}
